### ISSUE TITLE
OSError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by bhishanpdl** [bhishanpdl/DMstack_obsfile_Clusters#1]
While running the dmstacks commands given in this repo. I encountered this error while running the command 
```
processCcd.py input/ --id filename=trial0.fits --config isr.noise=5 --configfile processCcdConfig.py --clobber-config --output output
```

It runs for a while and after some time it spits out the error.

```
processCcd FATAL: Failed on dataId=DataId(initialdata={'filename': 'trial07.fits'}, tag=set([])): [Errno 20] Not a directory
Traceback (most recent call last):
1.  File "/opt/lsst/software/stack/Linux64/pipe_base/13.0/python/lsst/pipe/base/cmdLineTask.py", line 347, in __call__
    result = task.run(dataRef, **kwargs)
2.  File "/opt/lsst/software/stack/Linux64/pipe_base/13.0/python/lsst/pipe/base/timer.py", line 121, in wrapper
    res = func(self, *args, **keyArgs)
3.  File "/opt/lsst/software/stack/Linux64/pipe_tasks/13.0/python/lsst/pipe/tasks/processCcd.py", line 186, in run
    doUnpersist=False,
4.  File "/opt/lsst/software/stack/Linux64/pipe_base/13.0/python/lsst/pipe/base/timer.py", line 121, in wrapper
    res = func(self, *args, **keyArgs)
5.  File "/opt/lsst/software/stack/Linux64/pipe_tasks/13.0/python/lsst/pipe/tasks/characterizeImage.py", line 374, in run
    dataRef.put(charRes.exposure, "icExp")
6.  File "/opt/lsst/software/stack/Linux64/daf_persistence/13.0/python/lsst/daf/persistence/butlerSubset.py", line 216, in put
    self.butlerSubset.butler.put(obj, datasetType, self.dataId, doBackup=doBackup, **rest)
7.  File "/opt/lsst/software/stack/Linux64/daf_persistence/13.0/python/lsst/daf/persistence/butler.py", line 784, in put
    location.getRepository().write(location, obj)
8.  File "/opt/lsst/software/stack/Linux64/daf_persistence/13.0/python/lsst/daf/persistence/repository.py", line 144, in write
    return self._storage.write(butlerLocation, obj)
9.  File "/opt/lsst/software/stack/Linux64/daf_persistence/13.0/python/lsst/daf/persistence/posixStorage.py", line 229, in write
    self.persistence.persist(obj, storageList, additionalData)
10.  File "/opt/lsst/software/stack/Linux64/miniconda2/4.2.12.lsst1/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
11.  File "/opt/lsst/software/stack/Linux64/daf_persistence/13.0/python/lsst/daf/persistence/safeFileIo.py", line 126, in SafeFilename
    os.rename(tempName, name)
OSError: [Errno 20] Not a directory
```

It says NOT A DIRECTORY, but I checked all the files given above and they are there. Nothing is missing.

**Comment by bhishanpdl** [comment]
I was using wrong version of checkout from Simon Kruff github repo.

**Wrong** 
```
git clone https://github.com/SimonKrughoff/obs_file
cd obs_file
git checkout tickets/DM-6924 
```

**Correct**
```
git clone https://github.com/SimonKrughoff/obs_file
cd obs_file
git checkout 21fd0d51806c43bf335300a0bc97e409ed9c703e
```
