### ISSUE TITLE
IndexError: No viable PSF candidates survive

### ISSUE THREAD

**Issue by bhishanpdl** [bhishanpdl/DMstack_obsfile_Clusters#3]
**Error Log**

```
[vagrant@b1310fdd8d3c example]$ processCcd.py input/ --id filename=trial0.fits --config isr.noise=5 --configfile processCcdConfig.py --clobber-config --output output
root INFO: Loading config overrride file '/home/lsst/mnt/Research/DMstack/obs_file/config/processCcd.py'
root INFO: Running: /opt/lsst/software/stack/Linux64/pipe_tasks/13.0/bin/processCcd.py input/ --id filename=trial0.fits --config isr.noise=5 --configfile processCcdConfig.py --clobber-config --output output
processCcd INFO: Processing DataId(initialdata={'filename': 'trial0.fits'}, tag=set([]))
processCcd.isr INFO: FileIsr:  DataId(initialdata={'filename': 'trial0.fits'}, tag=set([]))
afw.image.MaskedImage WARN: Expected extension type not found: IMAGE
CameraMapper WARN: Key="EXPTIME" not in medata
CameraMapper WARN: Key="TAI" not in medata
CameraMapper WARN: Could not parse TAI = nan as an MJD date: Input values did not match the format class mjd
CameraMapper WARN: date is invalid; cannot offset it
processCcd.isr INFO: Setting variance: noise=5 ADU
processCcd.charImage INFO: Processing DataId(initialdata={'filename': 'trial0.fits'}, tag=set([]))
processCcd.charImage WARN: Source catalog detected and measured with placeholder or default PSF
processCcd.charImage.repair INFO: Identified 106 cosmic rays.
processCcd.charImage.detection INFO: Detected 1658 positive sources to 50 sigma.
processCcd.charImage.detection INFO: Resubtracting the background after object detection
processCcd.charImage.measurement INFO: Measuring 1658 sources (1658 parents, 0 children) 
processCcd.charImage.measurePsf INFO: Measuring PSF
processCcd.charImage.measurePsf INFO: PSF star selector found 661 candidates
processCcd.charImage.measurePsf.psfDeterminer WARN: Please provide at least one Image for me to update: reducing number of eigen components
processCcd.charImage.measurePsf.psfDeterminer WARN: Please provide at least one Image for me to update: reducing number of eigen components
processCcd.charImage.measurePsf.psfDeterminer WARN: Please provide at least one Image for me to update: reducing number of eigen components
processCcd FATAL: Failed on dataId=DataId(initialdata={'filename': 'trial0.fits'}, tag=set([])): No viable PSF candidates survive
Traceback (most recent call last):
  File "/opt/lsst/software/stack/Linux64/pipe_base/13.0/python/lsst/pipe/base/cmdLineTask.py", line 347, in __call__
    result = task.run(dataRef, **kwargs)
  File "/opt/lsst/software/stack/Linux64/pipe_base/13.0/python/lsst/pipe/base/timer.py", line 121, in wrapper
    res = func(self, *args, **keyArgs)
  File "/opt/lsst/software/stack/Linux64/pipe_tasks/13.0/python/lsst/pipe/tasks/processCcd.py", line 186, in run
    doUnpersist=False,
  File "/opt/lsst/software/stack/Linux64/pipe_base/13.0/python/lsst/pipe/base/timer.py", line 121, in wrapper
    res = func(self, *args, **keyArgs)
  File "/opt/lsst/software/stack/Linux64/pipe_tasks/13.0/python/lsst/pipe/tasks/characterizeImage.py", line 368, in run
    background = background,
  File "/opt/lsst/software/stack/Linux64/pipe_base/13.0/python/lsst/pipe/base/timer.py", line 121, in wrapper
    res = func(self, *args, **keyArgs)
  File "/opt/lsst/software/stack/Linux64/pipe_tasks/13.0/python/lsst/pipe/tasks/characterizeImage.py", line 426, in characterize
    background = background,
  File "/opt/lsst/software/stack/Linux64/pipe_base/13.0/python/lsst/pipe/base/timer.py", line 121, in wrapper
    res = func(self, *args, **keyArgs)
  File "/opt/lsst/software/stack/Linux64/pipe_tasks/13.0/python/lsst/pipe/tasks/characterizeImage.py", line 518, in detectMeasureAndEstimatePsf
    measPsfRes = self.measurePsf.run(exposure=exposure, sources=sourceCat, matches=matches)
  File "/opt/lsst/software/stack/Linux64/pipe_base/13.0/python/lsst/pipe/base/timer.py", line 121, in wrapper
    res = func(self, *args, **keyArgs)
  File "/opt/lsst/software/stack/Linux64/pipe_tasks/13.0/python/lsst/pipe/tasks/measurePsf.py", line 311, in run
    flagKey=self.usedKey)
  File "/opt/lsst/software/stack/Linux64/meas_algorithms/13.0/python/lsst/meas/algorithms/pcaPsfDeterminer.py", line 570, in determinePsf
    self._fitPsf(exposure, psfCellSet, actualKernelSize, nEigenComponents)
  File "/opt/lsst/software/stack/Linux64/meas_algorithms/13.0/python/lsst/meas/algorithms/pcaPsfDeterminer.py", line 183, in _fitPsf
    raise IndexError("No viable PSF candidates survive")
IndexError: No viable PSF candidates survive
```

**Comment by bhishanpdl** [comment]
**Solution** 
The `trial00.fits` file should have psf files with large enough values comparable to the galaxies in that cluster.
